# Generated by Django 3.1.5 on 2021-01-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
